/**
 * render.ts — the measured mechanics every view shares: what a cell says, how
 * wide a column gets, where a line breaks.
 *
 * Everything here was read off pwsh 7.6.5 at a pinned render width of 120 and
 * culture en-US, which are the capture's own settings
 * (`capture.renderWidth`, `capture.pinnedCulture`).
 *
 * THE FOUR THINGS THAT ARE NOT GUESSABLE
 *
 * 1. A FLOATING-POINT TABLE CELL IS NOT `"$x"`. It is `ToString("F")` — the
 *    culture's default fraction digits, no group separator. Measured on pwsh
 *    7.6.5, LINUX, with CurrentCulture pinned:
 *
 *      culture   1.5 in a table cell   1.5 elsewhere
 *      en-US     1.500                 1.5
 *      de-DE     1,500                 1,5
 *      zh-TW     1.500                 1.5
 *
 *    This table used to say zh-TW was `1.50`, which was the load-bearing claim
 *    in culture.ts's argument for hand-maintaining its data. zh-TW's
 *    NumberDecimalDigits is 3, like en-US's and de-DE's; only the INVARIANT
 *    culture is 2, and it is not a locale.
 *
 *    Format-LIST and Format-WIDE do not do this; they print 1.5. Only the table
 *    does, and only for floating-point values — an Int32 7 stays `7`, and
 *    negative zero is the one whole number that is NOT treated as an integer
 *    (`-0.000` in a table, `-0` in a list). Verified against `$v.ToString('F')`
 *    for 1.5, 0.0001, 1e21, 1234.5, 2.5, 0.125, -1.5 and negative zero.
 *
 * 2. COLUMN WIDTHS COME FROM EVERY OBJECT, NOT THE FIRST. The folklore is that
 *    Format-Table sizes on the first object and `-AutoSize` is what makes it
 *    look at the rest. Measured: a stream of twenty-one two-character values
 *    followed by a sixteen-character one produces a sixteen-wide column WITHOUT
 *    `-AutoSize`, and the same at one thousand objects. So the formatter
 *    buffers, and `-AutoSize` changed nothing on any input tried.
 *
 * 3. THE LAST COLUMN IS NEVER RIGHT-PADDED, AND A HIDDEN COLUMN STILL COUNTS.
 *    A left-aligned cell in the final column gets no trailing spaces, so
 *    `a2         b2         c2         d2` ends at 35 characters and not 43.
 *    But "final" means final in the COLUMN ARRAY, not the last one visible: when
 *    the terminal is too narrow and the last column collapses to zero width, the
 *    one before it starts being padded, and the line grows to exactly the
 *    terminal width. Both forms appear in the tests.
 *
 * 4. THE HEADER IS TRIMMED AND THE ROWS ARE NOT. The header row is generated by
 *    the wrapping writer, which right-trims; the underline and the data rows go
 *    through the single-line writer, which does not. That asymmetry is why a
 *    squeezed table has a 26-character header above a 30-character underline.
 */

import { DEFAULT_CULTURE, type CultureData } from './culture.ts';
import { formatDateGeneral } from './datetime.ts';
import { formatFixed, formatGeneral } from './numeric.ts';
import { toPSString } from './to-string.ts';
import { displayWidth, graphemeWidth, padLeft, padRight, truncateToWidth } from './width.ts';
import type { PSValue } from '../pipeline/psobject.ts';

/**
 * The width the conformance capture ran at (`capture.renderWidth`), and what a
 * redirected pwsh reports for `$Host.UI.RawUI.WindowSize.Width` on this
 * machine. Pinned rather than sniffed so a test cannot depend on the terminal
 * that happens to be running it.
 */
export const DEFAULT_RENDER_WIDTH = 120;

/** `Out-String -Width 1` is refused by pwsh; the minimum it accepts is 2. */
export const MIN_OUT_STRING_WIDTH = 2;

/**
 * Below this the table gives up entirely and prints only its blank lines —
 * measured at widths 2, 3 and 4, for one column and for two, with short headers
 * and long ones. Five is where output starts.
 */
export const MIN_TABLE_WIDTH = 5;

/** U+2026. Not three dots: pwsh 7 uses the single character. */
export const ELLIPSIS = '…';

/**
 * `$FormatEnumerationLimit`. Its default is 4, read off the live variable, and
 * it is what makes `@(1,2,3,4,5)` render as `{1, 2, 3, 4…}` in a cell.
 */
export const ENUMERATION_LIMIT = 4;

export type Alignment = 'left' | 'right';

// ---------------------------------------------------------------------------
// graphemes
// ---------------------------------------------------------------------------

let segmenter: Intl.Segmenter | null = null;

/**
 * Split into grapheme clusters. width.ts keeps its own copy of this private;
 * duplicating the three lines is better than widening that module's surface,
 * and the rule it encodes — never split a cluster — is enforced in both places.
 */
function clusters(text: string): string[] {
  segmenter ??= new Intl.Segmenter('en', { granularity: 'grapheme' });
  return [...segmenter.segment(text)].map((s) => s.segment);
}

// ---------------------------------------------------------------------------
// what a cell says
// ---------------------------------------------------------------------------

/**
 * Which conversion a cell uses for a floating-point value.
 *
 *   'table'  ToString("F") — the culture's default fraction digits.
 *            [pscustomobject]@{V=1.5} | Format-Table  ->  1.500  (en-US)
 *   'plain'  PowerShell's own G15, with the culture's decimal separator.
 *            [pscustomobject]@{V=1.5} | Format-List   ->  1.5
 *
 * The same value, two answers, in two views of one object. Measured, including
 * under de-DE where the plain form is `1,5` — so it is not the invariant
 * conversion either, and `1/3` is `0.333333333333333` (fifteen digits) rather
 * than the seventeen-digit round-trip form the `-f` operator produces.
 * Format-Wide, group headings and the elements inside a collection cell all use
 * 'plain'; only table CELLS use 'table'.
 */
export type NumericStyle = 'table' | 'plain';

/**
 * Above this a whole number is a Double or a Decimal rather than an Int64, and
 * the table's `F` rule applies to it:
 *
 *   pwsh: [pscustomobject]@{V=[int64]9223372036854775807} | Format-Table
 *     9223372036854775807
 *   pwsh: [pscustomobject]@{V=9223372036854775808} | Format-Table
 *     9223372036854775808.000
 *
 * The boundary is the one psobject.ts's `typeNameOf` uses, so the two cannot
 * disagree about what type a literal has.
 */
const INT64_MAX = 9223372036854775807;

/**
 * One element inside a collection cell.
 *
 * `$null` renders as the literal text `$null` here, which it does nowhere else:
 *
 *   pwsh: [pscustomobject]@{ V = @(1,$null,3) } | Format-Table  ->  {1, $null, 3}
 *   pwsh: "$(@(1,$null,3))"                                     ->  1  3
 *
 * A nested array collapses through `"$x"` instead, so `@(1,@(2,3))` is
 * `{1, 2 3}` — space-joined, not brace-wrapped a second time. And the elements
 * use the PLAIN numeric style even inside a table cell: `@(1.5,2.5)` is
 * `{1.5, 2.5}`, not `{1.500, 2.500}`. All measured.
 */
function collectionElement(value: PSValue, culture: CultureData): string {
  if (value === null || value === undefined) return '$null';
  if (Array.isArray(value) || value instanceof Uint8Array) return toPSString(value);
  return cellText(value, culture, 'plain');
}

/**
 * The text a table, list or wide cell shows for a value.
 *
 * The float rule in note 1 of the file header lives here, selected by `style`.
 * So does the collection rule: at most `$FormatEnumerationLimit` elements,
 * comma-space separated, in braces, with an ellipsis when there are more.
 *
 *   pwsh: @(1,2,3)      ->  {1, 2, 3}
 *   pwsh: @(1,2,3,4)    ->  {1, 2, 3, 4}
 *   pwsh: @(1,2,3,4,5)  ->  {1, 2, 3, 4…}
 *   pwsh: @()           ->  {}
 *
 * A DateTime follows the CULTURE here, unlike `"$date"` which does not.
 * Measured on pwsh 7.6.5, LINUX, on [datetime]::new(2020,3,4,5,6,7):
 *   en-US  3/4/2020 5:06:07<U+202F>AM     the separator is NOT a space
 *   de-DE  04.03.2020 05:06:07
 *   zh-TW  2020/3/4 上午5:06:07          designator FIRST, no space, one-digit hour
 *   "$x"   03/04/2020 05:06:07     (invariant — see to-string.ts)
 *
 * The zh-TW line used to read `2020/3/4 上午 05:06:07`, which is the pattern
 * a reader would guess from the en-US one rather than the pattern ICU reports.
 */
export function cellText(
  value: PSValue,
  culture: CultureData = DEFAULT_CULTURE,
  style: NumericStyle = 'plain',
): string {
  if (value === null || value === undefined) return '';
  if (typeof value === 'string') return value;
  if (typeof value === 'boolean') return value ? 'True' : 'False';
  if (typeof value === 'bigint') return value.toString();
  if (typeof value === 'number') {
    // A JavaScript number cannot say whether it is an Int32 or a whole Double,
    // so `[double]2.0` — which pwsh renders as `2.000` in a table — renders as
    // `2` here. Recorded rather than papered over; see the divergence test.
    //
    // NEGATIVE ZERO is excluded from that shortcut, because it is the one whole
    // number that cannot be an integer type: `Number.isInteger(-0)` is true and
    // `String(-0)` is `0`, which loses the sign pwsh keeps. Measured on pwsh
    // 7.6.5, LINUX:
    //   [pscustomobject]@{V=[double]::NegativeZero} | Format-Table  ->  -0.000
    //   ... | Format-List                                           ->  -0
    if (Number.isInteger(value) && !Object.is(value, -0) && Math.abs(value) <= INT64_MAX) {
      return String(value);
    }
    if (style === 'table') return formatFixed(value, culture.numberDecimalDigits, culture);
    return formatGeneral(value, 15, culture, true);
  }
  if (value instanceof Date) return formatDateGeneral(value, culture);
  if (Array.isArray(value) || value instanceof Uint8Array) {
    const items = Array.isArray(value) ? value : Array.from(value);
    const shown = items.slice(0, ENUMERATION_LIMIT).map((item) => collectionElement(item as PSValue, culture));
    const more = items.length > ENUMERATION_LIMIT ? ELLIPSIS : '';
    return `{${shown.join(', ')}${more}}`;
  }
  return toPSString(value);
}

/**
 * Which way a table column aligns.
 *
 * Measured right for Int32, Int64, Byte, Double, Decimal, Boolean, Char and an
 * enum; left for String, DateTime, TimeSpan, an array and `$null`. Boolean
 * being right-aligned is the surprise — `True` sits under a right-aligned `V`.
 *
 * The decision is per COLUMN and comes from the FIRST object's value, not from
 * each cell: a column whose first value is a number stays right-aligned even
 * when a later row holds a string.
 */
export function cellAlignment(value: PSValue): Alignment {
  if (typeof value === 'number' || typeof value === 'bigint' || typeof value === 'boolean') return 'right';
  return 'left';
}

// ---------------------------------------------------------------------------
// widths
// ---------------------------------------------------------------------------

/**
 * The columns a value occupies for SIZING purposes.
 *
 * An embedded newline counts as one column even though the terminal never draws
 * it, because pwsh sizes on the raw string: a cell holding "one\ntwo" produces
 * a seven-wide column while displaying only `one…`. Measured.
 */
export function sizingWidth(text: string): number {
  return displayWidth(text.replace(/[\r\n]/g, ' '));
}

/**
 * Hand out the available width to the columns, left to right.
 *
 * Each column takes its natural width if it fits, whatever is left if it does
 * not, and zero after that. Verified against a four-column table at widths
 * 44, 40, 30, 25, 20, 15, 12, 10, 8 and 5, and against a two-column one at
 * every width from 6 to 12.
 */
export function fitColumns(natural: readonly number[], width: number): number[] {
  const widths: number[] = [];
  let remaining = width;
  for (let index = 0; index < natural.length; index++) {
    const separator = index === 0 ? 0 : 1;
    if (remaining - separator <= 0) {
      widths.push(0);
      continue;
    }
    remaining -= separator;
    const take = Math.min(natural[index] ?? 0, remaining);
    widths.push(take);
    remaining -= take;
  }
  return widths;
}

/**
 * Cut a cell to its column.
 *
 * The ellipsis costs a column, so a one-wide column has no room for it and
 * truncates hard: a column of width 1 holding "bbbb" shows `b`, while width 2
 * shows `b…`. Measured; `truncateToWidth` alone answers the empty string at
 * width 1, which would silently drop the cell.
 */
export function truncateCell(text: string, width: number, alignment: Alignment = 'left'): string {
  if (width <= 0) return '';
  if (displayWidth(text) <= width) return text;

  const take = (budget: number, fromEnd: boolean): string => {
    const parts = clusters(text);
    const ordered = fromEnd ? [...parts].reverse() : parts;
    const kept: string[] = [];
    let used = 0;
    for (const cluster of ordered) {
      const w = graphemeWidth(cluster);
      if (used + w > budget) break;
      kept.push(cluster);
      used += w;
    }
    return fromEnd ? kept.reverse().join('') : kept.join('');
  };

  // No room for the marker, so the value is simply cut. Measured: a column of
  // width 1 holding "bbbb" shows `b`, where `truncateToWidth` alone answers the
  // empty string and would silently drop the cell.
  if (width <= displayWidth(ELLIPSIS)) return take(width, alignment === 'right');

  // A right-aligned column keeps its LAST characters and marks the front:
  //   pwsh: [pscustomobject]@{N=1234567} | Format-Table | Out-String -Width 5
  //     …4567
  // Truncating the tail instead would leave `1234…`, which reads as a
  // completely different number.
  if (alignment === 'right') return ELLIPSIS + take(width - displayWidth(ELLIPSIS), true);

  return truncateToWidth(text, width, ELLIPSIS);
}

/**
 * A newline in a non-wrapped cell truncates the value AND marks it:
 *
 *   pwsh: [pscustomobject]@{ A = "one`ntwo" } | Format-Table  ->  one…
 *
 * The ellipsis appears even though nothing was cut for width, which is how a
 * reader can tell a multi-line value from a short one.
 */
export function truncateAtNewline(text: string): string {
  const index = text.search(/[\r\n]/);
  return index === -1 ? text : text.slice(0, index) + ELLIPSIS;
}

/** Pad a cell into its column. Note 3 of the file header explains `isLast`. */
export function padCell(text: string, width: number, alignment: Alignment, isLast: boolean): string {
  if (alignment === 'right') return padLeft(text, width);
  return isLast ? text : padRight(text, width);
}

// ---------------------------------------------------------------------------
// wrapping
// ---------------------------------------------------------------------------

const isSpace = (cluster: string): boolean => cluster === ' ' || cluster === '\t';

/**
 * Break one line to `width`, the way `Format-Table -Wrap` and Format-List do.
 *
 * The rule looks like ordinary word wrap and is not, which four measurements
 * pin down:
 *
 *   'alpha beta gamma delta' at 10  ->  alpha / beta / gamma / delta
 *   'alpha beta gamma delta' at 11  ->  alpha beta / gamma delta
 *   'ab cdefghijk lm'        at  7  ->  ab cdef / ghijk / lm
 *   'supercalifragilistic and short' at 10 -> supercalif / ragilistic / " and short"
 *
 * Line one says the break must leave room for the space as well as the words,
 * so the limit is `width - 1` and `alpha beta` — exactly ten columns — does not
 * fit in ten. Line three says the wrap gives up when the NEXT word could not fit
 * on a line of its own and cuts at the width instead. Line four says the
 * remainder is emitted verbatim once it fits, leading space and all.
 *
 * The chunk KEEPS the whitespace it broke at. Format-List shows that space;
 * Format-Table's wrapping writer trims it away. Same algorithm, different
 * writer, and that is why `alpha ` and `alpha` are both correct answers.
 */
export function wrapText(text: string, width: number): string[] {
  if (width <= 0) return [text];
  const cells = clusters(text).map((cluster) => ({ cluster, width: graphemeWidth(cluster) }));

  const out: string[] = [];
  let start = 0;

  const widthFrom = (from: number, to: number): number => {
    let total = 0;
    for (let i = from; i < to; i++) total += cells[i]?.width ?? 0;
    return total;
  };

  while (widthFrom(start, cells.length) > width) {
    // The last whitespace whose chunk — including that whitespace — fits.
    let breakAt = -1;
    let used = 0;
    for (let i = start; i < cells.length; i++) {
      const cell = cells[i];
      if (cell === undefined) break;
      used += cell.width;
      if (used > width) break;
      if (isSpace(cell.cluster)) breakAt = i;
    }

    if (breakAt !== -1) {
      // Would the next word fit on a line by itself? If not, the wrap cannot
      // help and pwsh cuts at the width instead.
      let wordEnd = breakAt + 1;
      while (wordEnd < cells.length && !isSpace(cells[wordEnd]?.cluster ?? ' ')) wordEnd += 1;
      if (widthFrom(breakAt + 1, wordEnd) > width) breakAt = -1;
    }

    if (breakAt !== -1) {
      out.push(cells.slice(start, breakAt + 1).map((c) => c.cluster).join(''));
      start = breakAt + 1;
      continue;
    }

    let taken = 0;
    let end = start;
    while (end < cells.length && taken + (cells[end]?.width ?? 0) <= width) {
      taken += cells[end]?.width ?? 0;
      end += 1;
    }
    if (end === start) end = start + 1; // a single cluster wider than the column
    out.push(cells.slice(start, end).map((c) => c.cluster).join(''));
    start = end;
  }

  out.push(cells.slice(start).map((c) => c.cluster).join(''));
  return out;
}

/** Split on newlines first, then wrap each piece. Both views need this order. */
export function wrapLines(text: string, width: number): string[] {
  return text.split(/\r\n|\r|\n/).flatMap((line) => wrapText(line, width));
}

/** Right-trim, which is what the wrapping writer does and the single-line one does not. */
export const trimEnd = (line: string): string => line.replace(/[ \t]+$/, '');
